### ISSUE TITLE
KVError: there is no KV namespace bound to the script

### ISSUE THREAD

**Issue by carlsonorozco** [samuelcolvin/edge-mock#9]
Hi @samuelcolvin,

I got the issue of __STATIC_CONTENT undefined. Kindly refer to this code. 

https://github.com/carlsonorozco/my-ts-project/blob/main/test/handler.test.ts

```
➜  my-ts-project (main) ✔ npm run test

> worker-typescript-template@1.0.0 test /Users/Hello/my-ts-project
> jest --config jestconfig.json --verbose

 FAIL  test/handler.test.ts
  handle
    ✕ handle GET (2 ms)

  ● handle › handle GET

    KVError: there is no KV namespace bound to the script

      2 |
      3 | export async function handleEvent(event: FetchEvent): Promise<Response> {
    > 4 |   const testResponse = await getAssetFromKV(event, {
        |                              ^
      5 |     mapRequestToAsset: request => {
      6 |       return new Request(`https://example.com/error/404.html`, event.request)
      7 |     }

      at node_modules/@cloudflare/kv-asset-handler/dist/index.js:104:15
      at node_modules/@cloudflare/kv-asset-handler/dist/index.js:8:71
      at Object.<anonymous>.__awaiter (node_modules/@cloudflare/kv-asset-handler/dist/index.js:4:12)
      at Object.getAssetFromKV (node_modules/@cloudflare/kv-asset-handler/dist/index.js:98:44)
      at Object.handleEvent (src/handler.ts:4:30)
      at Object.<anonymous> (test/handler.test.ts:20:26)

Test Suites: 1 failed, 1 total
Tests:       1 failed, 1 total
Snapshots:   0 total
Time:        2.411 s, estimated 3 s
Ran all test suites.
```

**Comment by samuelcolvin** [comment]
I'm afk, but will look later.

Try importing the handler inside the test?

**Comment by carlsonorozco** [comment]
Hi @samuelcolvin,

Thank you. I was able to inject the handler into the test and looks like the `__STATIC_CONTENT` is now defined.
```
const { handleEvent } = require('../src/handler')
```

Although, got a new error 😅

```
ReferenceError: HTMLRewriter is not defined
```

I believe this is related to https://github.com/samuelcolvin/edge-mock/issues/6

**Comment by samuelcolvin** [comment]
Yes, currently `HTMLRewriter` is not implemented, you would need to create your own mock implantation, also happy to accept a PR to add it here.

**Comment by samuelcolvin** [comment]
You might be able to use [parsed-html-rewriter](https://github.com/worker-tools/parsed-html-rewriter).
